config/routes.rb
Rails.application.routes.draw do

  resources :kategories
  resources :produkts
  resources :warenkorbpositions
  resources :warenkorbs
  resources :bestellpositions
  resources :bestellungs
  resources :feeds do 
    member do
      delete :delete_image_attachment
    end
    get 'details', to: 'feeds#details'
  end
  
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "register" => "users#new"
  post "users" => "users#create"

  get "admin" => "bookings#dashboard"
  get "bestellemail" => "brotbestellscheins#bestellemail"
  put "bst_auf_schein" => "brotbestellscheins#bst_auf_schein"
  get "schein_aus_bst" => "brotbestellscheins#schein_aus_bst"
  get "standard" => "brotbestellungs#standard"
  post "contact" => "home#contactmail"
  post "anfrage_form" => "anfrages#create"
  get "packzettel" => "brotbestellscheins#packzettel"
  get "packzettel_show/:datum" => "brotbestellscheins#packzettel_show"

  resources :brottyps
  resources :openhours
  resources :brotbestellscheins
  resources :brotbestellposis
  resources :brotbestellungs do
    collection { get 'admin_order' }
  end
  resources :brotsortes
  resources :mieters
  resources :fewos
  resources :bookings do
    member do
      get "bestaetigen"
    end
    collection { get 'dashboard' }
  end
  resources :anfrages do
    get "antwort" => "anfrages#antwort"
  end

  get "home/index"
  get "home/hof"
  get "home/biogas"
  get "home/ausbildung"
  get '/home/ferienwohnung', to: 'home#fw', as: "home_fw"
  get "home/getcalendardates"
  get "home/hofladen"
  get "home/kontakt"
  get "home/thanks"

  get "start/index"
  root "home#index"

  get "shop" => "shop#index", as: :shop
  get "shop/produktliste" => "shop#produktliste"
  get "shop/produkt" => "shop#produkt"
  get "shop/warenkorb" => "shop#warenkorb"
  get "shop/kasse" => "shop#kasse"

  get "shop/kategorie/:id" => "shop#kategorie"

  

end

app/models/anfrage.rb
class Anfrage < ApplicationRecord
  validates :name, :presence => true

end

app/models/bestellung.rb
class Bestellung < ApplicationRecord
  belongs_to :user
  has_many :bestellpositions
end

app/models/brotbestellung.rb
class Brotbestellung < ApplicationRecord
  has_many :brotbestellposi, dependent: :destroy
  accepts_nested_attributes_for :brotbestellposi, :reject_if => proc { |attributes| attributes['menge'].blank? || (attributes['menge'].to_i < 1)}, allow_destroy: true
  belongs_to :brotbestellschein, optional: true

  validates_length_of :brotbestellposi, :minimum => 1, message: "muss mindestens einmal vorhanden sein!"
  validates :name, presence: true

  amoeba do
    enable
  end

  def versendet
   self.brotbestellschein.present? && self.brotbestellschein.versendet.present?
  end

  def vollname
    (self.vorname.present? ? "#{self.vorname} " : "") + (self.name.present? ? self.name : "") 
  end

end

app/models/brotsorte.rb
class Brotsorte < ApplicationRecord
  has_many :brotbestellposi
  belongs_to :brottyp
  has_one_attached :brotbild
  # validates_attachment_content_type :brotbild, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  #validates_attachment_presence :brotbild
end

app/models/brottyp.rb
class Brottyp < ApplicationRecord
  has_many :brotsortes
end

app/models/event.rb
class Event
  attr_accessor :date

  def initialize(date)
    @date = date
  end

  def start_time
    @date
  end
end

app/models/feed.rb
class Feed < ApplicationRecord
    default_scope { order(priority: :asc) }
    has_many_attached :feedbilder
end

app/models/fewo.rb
class Fewo < ApplicationRecord
  acts_as_bookable  time_type: :range,
                    capacity_type: :closed,
                    bookable_across_occurrences: true

end

app/models/kategorie.rb
class Kategorie < ApplicationRecord
  has_many :produkts
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :telefon, :text

  validates :name, :presence => true
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+[a-z]{2,})\z/i, message: "ist ungültig!",:allow_nil => true, :allow_blank => true
end

app/models/mieter.rb
class Mieter < ApplicationRecord
  acts_as_booker time_type: :range, bookable_across_occurrences: true
  def name_with_initial
    "ID: #{id} / #{vorname} #{name}"
  end
end

app/models/openhour.rb
class Openhour < ApplicationRecord
    default_scope { order(reihenfolge: :asc) }
end

app/models/produkt.rb
class Produkt < ApplicationRecord
  has_many :warenkorbpositions
  has_many :bestellpositions
  belongs_to :kategorie
  has_one_attached :produktbild
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bestellungs
  has_many :warenkorbs


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false},
          length: {maximum: 50}, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true,  uniqueness: true
  validates :password, length: {minimum: 5}

end

app/models/warenkorb.rb
class Warenkorb < ApplicationRecord
  belongs_to :user, optional: true
  has_many :warenkorbpositions, :dependent => :destroy 
end

app/controllers/mieters_controller.rb
class MietersController < ApplicationController
  before_action :authorize


  def index
    @mieters = Mieter.all
  end

  def show

  end

  def new
    @mieter = Mieter.new
  end

  def create
    @mieter = Mieter.new(mieter_params)
    if @mieter.save
      respond_to do |format|
        format.html { redirect_to mieters_url, notice: 'Mieter erstellt!' }
        format.json { render json: @mieter }
      end
    else
      render 'new'
    end
  end

  def destroy
    @mieter = Mieter.find(params[:id])
    @mieter.destroy
    respond_to do |format|
      format.html { redirect_to mieters_url, notice: 'Mieter gelöscht!' }
      format.json { head :no_content }
    end
  end

  def edit
    @mieter = Mieter.find(params[:id])
  end

  def update
    @mieter = Mieter.find(params[:id])
    respond_to do |format|
      if @mieter.update(mieter_params)
        format.html { redirect_to mieters_path, notice: 'Mieter erfolgreich gespeichert.' }
        format.json { render :show, status: :ok, location: @mieter }
      else
        format.html { render :edit }
        format.json { render json: @mieter.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def mieter_params
    params.require(:mieter).permit!
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/fewo_helper.rb
module FewoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mieter_helper.rb
module MieterHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/mieters/create.html.haml
%h1 Mieter#create
%p Find me in app/views/mieter/create.html.haml

app/views/mieters/edit.html.haml
%h2.title.is-4 Mieter bearbeiten
= form_for @mieter, url: {action: "update"}, :html => {:class => 'ui form'} do |f|
  .two.fields
    .field
      = f.label :vorname, class: 'label'
      = f.text_field :vorname, class: 'input', type: 'text'
    .field
      = f.label :name, class: 'label'
      = f.text_field :name, class: 'input', type: 'text'
  .two.fields
    .field
      = f.label :telefon, class: 'label'
      = f.text_field :telefon, class: 'input', type: 'tel'
    .field
      = f.label :email, class: 'label'
      = f.text_field :email, class: 'input', type: 'email'
  .two.fields
    .field
      = f.label :strasse, class: 'label'
      = f.text_field :strasse, class: 'input', type: 'text'
    .field
      = f.label :plz, class: 'label'
      = f.text_field :plz, class: 'input', type: 'text'
  .two.fields
    .field
      = f.label :ort, class: 'label'
      = f.text_field :ort, class: 'input', type: 'text'
    .field
      = f.label :notiz, class: 'label'
      = f.text_field :notiz, class: 'input', type: 'text'
  .actions
    = f.submit 'Mieter anlegen', class: 'button ui green is-primary', type: 'submit'
%br/
.ui.divider
%h3 Buchungen
- if @mieter.bookings.size > 0
  %table.ui.table

    %thead
      %tr
        %th Name
        %th Pers. Anzahl
        %th Zeitraum
        %th Notiz
        %th Typ
        %th
        %th

    %tbody
      - @mieter.bookings.sort_by(&:time_start).reverse.each do |booking|
        %tr
          %td
            = "#{booking.booker.vorname} #{booking.booker.name}"
          %td
            = booking.amount
          %td
            =booking.time_start.strftime("%d.%m.%Y")
            = "-"
            =booking.time_end.strftime("%d.%m.%Y")
          %td
            = booking.notiz.truncate(30)
          %td
            - case booking.typ
            - when "std"
              = "Normal"
            - when "airbnb"
              = "Airbnb"
            - when "block"
              = "Blocker"
          %td
            = link_to edit_booking_path(booking), :id => booking.id, :class => "popup",:"data-content" => "Bearbeiten" do
              %i.edit.outline.icon
          %td
            = link_to  booking_path(booking), method: :delete, :class => "popup", data: { confirm: 'Wirklich löschen?', content: "Löschen" }, style: "margin-left: 5px" do
              %i.trash.alternate.outline.icon
    
- else
  .ui.message
    keine Buchungen von diesen Mieter 

app/views/mieters/index.html.haml
%h2 Mieter
%table.table.ui.mieterTable
  %thead
    %tr
      %th #
      %th Vorname
      %th Name
      %th Telefon
      %th E-Mail
      %th Strasse
      %th PLZ
      %th Ort
      %th Notiz
      %th
      %th
  %tbody
    - @mieters.each do |mieter|
      %tr
        %td= mieter.id
        %td= mieter.vorname
        %td= mieter.name
        %td= mieter.telefon
        %td= mieter.email
        %td= mieter.strasse
        %td= mieter.plz
        %td= mieter.ort
        %td= mieter.notiz.truncate(30)
        %td
          = link_to edit_mieter_path(mieter), :class => "popup",:"data-content" => "Bearbeiten" do
            %i.edit.outline.icon
        %td
          = link_to  mieter, method: :delete, :class => "popup", data: { confirm: 'Wirklich löschen?', content: "Löschen" }, style: "margin-left: 5px" do
            %i.trash.alternate.outline.icon

:javascript
  $(document).ready(function () {
    var mieterTable = $('.mieterTable').DataTable({
      columnDefs: [
        {bSortable: false, targets: [9,10]} 
      ],
      "order": [[ 2, "asc" ], [ 1, "asc" ]]
    });

    mieterTable.buttons().container().appendTo( $('div.nine.column:eq(0)', mieterTable.table().container()) );
    
    $('.ui.button', mieterTable.buttons().container()).addClass('basic')
  });

app/views/mieters/new.html.haml
.columns.is-mobile
  .column.is-half.is-offset-one-quarter

    .box
      %h2.title.is-4 Neuen Mieter anlegen
      = form_for @mieter, url: {action: "create"} do |f|
        .field.is-horizontal
          .field-label.is-normal
            = f.label :vorname, class: 'label'
          .field-body
            .field
              .control
                = f.text_field :vorname, class: 'input', type: 'text'
        .field.is-horizontal
          .field-label.is-normal
            = f.label :name, class: 'label'
          .field-body
            .field
              .control
                = f.text_field :name, class: 'input', type: 'text'
        .field.is-horizontal
          .field-label.is-normal
            = f.label :telefon, class: 'label'
          .field-body
            .field
              .control
                = f.text_field :telefon, class: 'input', type: 'tel'
        .field.is-horizontal
          .field-label.is-normal
            = f.label :email, class: 'label'
          .field-body
            .field
              .control
                = f.text_field :email, class: 'input', type: 'email'
        .field.is-horizontal
          .field-label.is-normal
            = f.label :strasse, class: 'label'
          .field-body
            .field
              .control
                = f.text_field :strasse, class: 'input', type: 'text'
        .field.is-horizontal
          .field-label.is-normal
            = f.label :plz, class: 'label'
          .field-body
            .field
              .control
                = f.text_field :plz, class: 'input', type: 'text'
        .field.is-horizontal
          .field-label.is-normal
            = f.label :ort, class: 'label'
          .field-body
            .field
              .control
                = f.text_field :ort, class: 'input', type: 'text'
        .field.is-horizontal
          .field-label.is-normal
          .field-body
            .field
              .control
                = f.submit 'Mieter anlegen', class: 'button is-primary', type: 'submit'