config/routes.rb
Rails.application.routes.draw do

  resources :kategories
  resources :produkts
  resources :warenkorbpositions
  resources :warenkorbs
  resources :bestellpositions
  resources :bestellungs
  resources :feeds do 
    member do
      delete :delete_image_attachment
    end
    get 'details', to: 'feeds#details'
  end
  
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "register" => "users#new"
  post "users" => "users#create"

  get "admin" => "bookings#dashboard"
  get "bestellemail" => "brotbestellscheins#bestellemail"
  put "bst_auf_schein" => "brotbestellscheins#bst_auf_schein"
  get "schein_aus_bst" => "brotbestellscheins#schein_aus_bst"
  get "standard" => "brotbestellungs#standard"
  post "contact" => "home#contactmail"
  post "anfrage_form" => "anfrages#create"
  get "packzettel" => "brotbestellscheins#packzettel"
  get "packzettel_show/:datum" => "brotbestellscheins#packzettel_show"

  resources :brottyps
  resources :openhours
  resources :brotbestellscheins
  resources :brotbestellposis
  resources :brotbestellungs do
    collection { get 'admin_order' }
  end
  resources :brotsortes
  resources :mieters
  resources :fewos
  resources :bookings do
    member do
      get "bestaetigen"
    end
    collection { get 'dashboard' }
  end
  resources :anfrages do
    get "antwort" => "anfrages#antwort"
  end

  get "home/index"
  get "home/hof"
  get "home/biogas"
  get "home/ausbildung"
  get '/home/ferienwohnung', to: 'home#fw', as: "home_fw"
  get "home/getcalendardates"
  get "home/hofladen"
  get "home/kontakt"
  get "home/thanks"

  get "start/index"
  root "home#index"

  get "shop" => "shop#index", as: :shop
  get "shop/produktliste" => "shop#produktliste"
  get "shop/produkt" => "shop#produkt"
  get "shop/warenkorb" => "shop#warenkorb"
  get "shop/kasse" => "shop#kasse"

  get "shop/kategorie/:id" => "shop#kategorie"

  

end

app/models/anfrage.rb
class Anfrage < ApplicationRecord
  validates :name, :presence => true

end

app/models/bestellung.rb
class Bestellung < ApplicationRecord
  belongs_to :user
  has_many :bestellpositions
end

app/models/brotsorte.rb
class Brotsorte < ApplicationRecord
  has_many :brotbestellposi
  belongs_to :brottyp
  has_one_attached :brotbild
  # validates_attachment_content_type :brotbild, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  #validates_attachment_presence :brotbild
end

app/models/brottyp.rb
class Brottyp < ApplicationRecord
  has_many :brotsortes
end

app/models/event.rb
class Event
  attr_accessor :date

  def initialize(date)
    @date = date
  end

  def start_time
    @date
  end
end

app/models/feed.rb
class Feed < ApplicationRecord
    default_scope { order(priority: :asc) }
    has_many_attached :feedbilder
end

app/models/fewo.rb
class Fewo < ApplicationRecord
  acts_as_bookable  time_type: :range,
                    capacity_type: :closed,
                    bookable_across_occurrences: true

end

app/models/kategorie.rb
class Kategorie < ApplicationRecord
  has_many :produkts
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :telefon, :text

  validates :name, :presence => true
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+[a-z]{2,})\z/i, message: "ist ungültig!",:allow_nil => true, :allow_blank => true
end

app/models/mieter.rb
class Mieter < ApplicationRecord
  acts_as_booker time_type: :range, bookable_across_occurrences: true
  def name_with_initial
    "ID: #{id} / #{vorname} #{name}"
  end
end

app/models/openhour.rb
class Openhour < ApplicationRecord
    default_scope { order(reihenfolge: :asc) }
end

app/models/produkt.rb
class Produkt < ApplicationRecord
  has_many :warenkorbpositions
  has_many :bestellpositions
  belongs_to :kategorie
  has_one_attached :produktbild
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bestellungs
  has_many :warenkorbs


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false},
          length: {maximum: 50}, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true,  uniqueness: true
  validates :password, length: {minimum: 5}

end

app/models/warenkorb.rb
class Warenkorb < ApplicationRecord
  belongs_to :user, optional: true
  has_many :warenkorbpositions, :dependent => :destroy 
end

app/controllers/brotsortes_controller.rb
class BrotsortesController < ApplicationController
  before_action :set_brotsorte, only: [:show, :edit, :update, :destroy]
  before_action :authorize


  # GET /brotsortes
  # GET /brotsortes.json
  def index
    @brotsortes = Brotsorte.all
  end

  # GET /brotsortes/1
  # GET /brotsortes/1.json
  def show
  end

  # GET /brotsortes/new
  def new
    @brotsorte = Brotsorte.new
  end

  # GET /brotsortes/1/edit
  def edit
  end

  # POST /brotsortes
  # POST /brotsortes.json
  def create
    @brotsorte = Brotsorte.new(brotsorte_params)

    respond_to do |format|
      if @brotsorte.save
        format.html { redirect_to @brotsorte, notice: 'Brotsorte was successfully created.' }
        format.json { render :show, status: :created, location: @brotsorte }
      else
        format.html { render :new }
        format.json { render json: @brotsorte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brotsortes/1
  # PATCH/PUT /brotsortes/1.json
  def update
    respond_to do |format|
      if @brotsorte.update(brotsorte_params)
        format.html { redirect_to @brotsorte, notice: 'Brotsorte was successfully updated.' }
        format.json { render :show, status: :ok, location: @brotsorte }
      else
        format.html { render :edit }
        format.json { render json: @brotsorte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brotsortes/1
  # DELETE /brotsortes/1.json
  def destroy
    @brotsorte.destroy
    respond_to do |format|
      format.html { redirect_to brotsortes_url, notice: 'Brotsorte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brotsorte
      @brotsorte = Brotsorte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brotsorte_params
      params.require(:brotsorte).permit(:name, :aktiv, :ausverkauft, :brottyp_id, :brotbild)
    end
end

app/helpers/brotsortes_helper.rb
module BrotsortesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/fewo_helper.rb
module FewoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mieter_helper.rb
module MieterHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/brotsortes/_form.html.haml
= form_for @brotsorte, :html => {:class => 'ui form', multipart: true } do |f|
  - if @brotsorte.errors.any?
    #error_explanation
      %h2= "#{pluralize(@brotsorte.errors.count, "error")} prohibited this brotsorte from being saved:"
      %ul
        - @brotsorte.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    %label Kategorie
    = f.select :brottyp_id, options_from_collection_for_select(Brottyp.all, :id, :name, f.object.brottyp_id),{}, {class: 'ui dropdown'}
  .field
    .ui.checkbox
      = f.check_box :aktiv, :class => 'checkbox'
      = f.label :aktiv
  -# .field
    .ui.checkbox
      = f.check_box :ausverkauft, :class => 'checkbox'
      = f.label :ausverkauft
  .field
    = f.label :brotbild
    = f.file_field :brotbild

  .actions
    = link_to 'Zurück', brotsortes_path, :class  => 'ui button red basic'
    = f.submit 'Speichern', :class  => 'ui button green basic'

app/views/brotsortes/edit.html.haml
%h1 Editing brotsorte

= render 'form'

= link_to 'Anzeigen', @brotsorte
\|
= link_to 'Zurück', brotsortes_path

app/views/brotsortes/index.html.haml
%h1 Brotsorten

= link_to 'Neue Brotsorte', new_brotsorte_path, class: 'button ui green basic'
%table.ui.table
  %thead
    %tr
      %th Name
      %th Aktiv
      -# %th Ausverkauft
      %th
      %th
      %th

  %tbody
    - @brotsortes.group_by(&:brottyp).each do |key, group|
      %tr
        %td{:colspan => 6, :style => "background-color: #eee"}
          %strong
            = key.name rescue "-"
      - group.each do |brotsorte|
        %tr
          %td= brotsorte.name
          %td= check(brotsorte.aktiv)
          -# %td= check(brotsorte.ausverkauft)
          %td= link_to 'Anzeigen', brotsorte
          %td= link_to 'Bearbeiten', edit_brotsorte_path(brotsorte)
          %td= link_to 'Löschen', brotsorte, method: :delete, data: { confirm: 'Wirklich löschen?' }

%br

app/views/brotsortes/new.html.haml
%h1 Neue Brotsorte

= render 'form'

app/views/brotsortes/show.html.haml
-# %p#notice= notice

%p
  %b Name:
  = @brotsorte.name
%p
  %b Aktiv:
  = @brotsorte.aktiv
%p
  %b Ausverkauft:
  = @brotsorte.ausverkauft
%p
  %b Kategorie:
  = @brotsorte.brottyp.name

= image_tag @brotsorte.brotbild, {:width => '300'}
%br

= link_to 'Bearbeiten', edit_brotsorte_path(@brotsorte)
\|
= link_to 'Zurück', brotsortes_path