config/routes.rb
Rails.application.routes.draw do

  resources :kategories
  resources :produkts
  resources :warenkorbpositions
  resources :warenkorbs
  resources :bestellpositions
  resources :bestellungs
  resources :feeds do 
    member do
      delete :delete_image_attachment
    end
    get 'details', to: 'feeds#details'
  end
  
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "register" => "users#new"
  post "users" => "users#create"

  get "admin" => "bookings#dashboard"
  get "bestellemail" => "brotbestellscheins#bestellemail"
  put "bst_auf_schein" => "brotbestellscheins#bst_auf_schein"
  get "schein_aus_bst" => "brotbestellscheins#schein_aus_bst"
  get "standard" => "brotbestellungs#standard"
  post "contact" => "home#contactmail"
  post "anfrage_form" => "anfrages#create"
  get "packzettel" => "brotbestellscheins#packzettel"
  get "packzettel_show/:datum" => "brotbestellscheins#packzettel_show"

  resources :brottyps
  resources :openhours
  resources :brotbestellscheins
  resources :brotbestellposis
  resources :brotbestellungs do
    collection { get 'admin_order' }
  end
  resources :brotsortes
  resources :mieters
  resources :fewos
  resources :bookings do
    member do
      get "bestaetigen"
    end
    collection { get 'dashboard' }
  end
  resources :anfrages do
    get "antwort" => "anfrages#antwort"
  end

  get "home/index"
  get "home/hof"
  get "home/biogas"
  get "home/ausbildung"
  get '/home/ferienwohnung', to: 'home#fw', as: "home_fw"
  get "home/getcalendardates"
  get "home/hofladen"
  get "home/kontakt"
  get "home/thanks"

  get "start/index"
  root "home#index"

  get "shop" => "shop#index", as: :shop
  get "shop/produktliste" => "shop#produktliste"
  get "shop/produkt" => "shop#produkt"
  get "shop/warenkorb" => "shop#warenkorb"
  get "shop/kasse" => "shop#kasse"

  get "shop/kategorie/:id" => "shop#kategorie"

  

end

app/models/anfrage.rb
class Anfrage < ApplicationRecord
  validates :name, :presence => true

end

app/models/bestellung.rb
class Bestellung < ApplicationRecord
  belongs_to :user
  has_many :bestellpositions
end

app/models/brotsorte.rb
class Brotsorte < ApplicationRecord
  has_many :brotbestellposi
  belongs_to :brottyp
  has_one_attached :brotbild
  # validates_attachment_content_type :brotbild, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  #validates_attachment_presence :brotbild
end

app/models/brottyp.rb
class Brottyp < ApplicationRecord
  has_many :brotsortes
end

app/models/event.rb
class Event
  attr_accessor :date

  def initialize(date)
    @date = date
  end

  def start_time
    @date
  end
end

app/models/feed.rb
class Feed < ApplicationRecord
    default_scope { order(priority: :asc) }
    has_many_attached :feedbilder
end

app/models/fewo.rb
class Fewo < ApplicationRecord
  acts_as_bookable  time_type: :range,
                    capacity_type: :closed,
                    bookable_across_occurrences: true

end

app/models/kategorie.rb
class Kategorie < ApplicationRecord
  has_many :produkts
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :telefon, :text

  validates :name, :presence => true
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+[a-z]{2,})\z/i, message: "ist ungültig!",:allow_nil => true, :allow_blank => true
end

app/models/mieter.rb
class Mieter < ApplicationRecord
  acts_as_booker time_type: :range, bookable_across_occurrences: true
  def name_with_initial
    "ID: #{id} / #{vorname} #{name}"
  end
end

app/models/openhour.rb
class Openhour < ApplicationRecord
    default_scope { order(reihenfolge: :asc) }
end

app/models/produkt.rb
class Produkt < ApplicationRecord
  has_many :warenkorbpositions
  has_many :bestellpositions
  belongs_to :kategorie
  has_one_attached :produktbild
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bestellungs
  has_many :warenkorbs


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false},
          length: {maximum: 50}, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true,  uniqueness: true
  validates :password, length: {minimum: 5}

end

app/models/warenkorb.rb
class Warenkorb < ApplicationRecord
  belongs_to :user, optional: true
  has_many :warenkorbpositions, :dependent => :destroy 
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  layout 'shop/shop'
  before_action :set_openhours


  def index
  end
  
  def produktliste
  end

  def kategorie
    @kategorie = Kategorie.find(params[:id])
    @produkts = Produkt.where(kategorie: @kategorie)
  end

  def warenkorb
  end

  def kasse
    
  end
  
  
  private
  
  def set_openhours
    @openhours = Openhour.all
  end
  
  
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/fewo_helper.rb
module FewoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mieter_helper.rb
module MieterHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/layouts/shop/_cartbox.html.haml
.cart-box
  .card
    .card-body
      %h3.card-title.mt-3.mb-4.text-orange Mein Warenkorb
      %table.table.table-borderless.text-green.table-sm
        %tr
          %td 3x Weizenbrötchen
          %td 2,25 €
        %tr
          %td 2x Mehrkorn
          %td 1,25 €
        %tr
          %td 1x Dinkel Sesam	
          %td 1,75 €
        %tr.font-weight-bold
          %td.pt-2 Summe
          %td.pt-2 6,30 €
      -# %h4.text-green Ihr Warenkorb ist leer.
      .form-group
        %a.btn.btn-success.btn-small.btn-block.text-white.no-hover.my-0{:type => "submit"} zur Kasse
      .form-group.mb-0
        %a.no-hover.text-orange{:href => "#"} Warenkorb bearbeiten

app/views/layouts/shop/_footer.html.haml
.row.bg-yellow2.roomy-90.border-top
  .col-lg-4.offset-lg-1.mx-lg-5.mx-md-3
    %h1
      Kontakt
    %p.text-green
      %strong
        Barbara, Karl-Heinz und Sebastian Vogler
      %br
      Tiebrink 5
      %br
      37619 Kirchbrak
      %br
      Telefon: +49 5533 1514
      %br
      Telefax: +49 5533 6215
      %br
      %a{:href => "mailto:info@voglerhof.de"}
        E-Mail: info@voglerhof.de
      %br
      Internet: www.voglerhof.de
      %br
      %br
      %br
      Öko-Kontrollstelle: ÖKO DE 006
      %br
      .sub-logo-container-footer
        %a{:href => "http://www.bioland.de"}
          = image_tag 'home/header/bioland.svg'
        %a{:href => "http://www.bioland.de"}
          = image_tag 'home/header/biosiegel.svg'
        %a{:href => "#"}
          = image_tag 'home/header/eu_bio_logo.svg'
        %a{:href => "https://www.ml.niedersachsen.de/themen/entwicklung_laendlichen_raums/eufoerderprogramme_zur_entwicklung_im_laendlichen_raum/eu-foerderung-in-niedersachsen-147111.html"}
          = image_tag 'eu.png'



  .col-lg-6.offset-lg-1.mx-md-3.my-md-5.my-lg-0
    = form_for :message, :url => contact_path, :remote => true, :html =>{:class => 'contact-form'} do |form|
      .form-group
        = form.text_field :name, class: 'form-control', placeholder: 'Name'
      .form-row
        .form-group.col-6
          = form.text_field :email, class: 'form-control', placeholder: 'E-Mail'
        .form-group.col-6
          = form.text_field :telefon, class: 'form-control', placeholder: 'Telefon'
      .form-group
        = form.text_area :text, class: 'form-control', rows: 8, placeholder: 'Nachricht'
      %button.btn.btn-small.pull-right{:href => "/", :style => "width: 100%",:type => "submit"}
        %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
        Senden
    .form-notice


#contact-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "Contact Form", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered{:role => "document"}
    .modal-content.border-left
      .modal-body
        %p.text-green Danke, Ihre Nachricht wurde erfolgreich übermittelt.
      .modal-footer
        %button.btn.btn-primary.btn-small{"data-dismiss" => "modal", :type => "button"} Schliessen

app/views/layouts/shop/_header.html.haml
- if @openhours.present?
  .open-at.d-none.d-lg-block
    %h3
      Hofladen
      %br/
      Öffnungszeiten:
    .ui.list-group.list-group-flush{:style => "margin:0"}
      - @openhours.each do |openhour|
        - if !openhour.geschlossen
          .list-group-item
            - if openhour.without_time
              = "#{openhour.tag}"
            - else
              = "#{openhour.tag}: #{openhour.start.strftime("%H:%M")} - #{openhour.ende.strftime("%H:%M")}"
        - else
          .list-group-item
            = "#{openhour.tag}: geschlossen"
.sub-logo-container
  %a.sub-logo{:href => "http://www.bioland.de"}
    = image_tag 'home/header/bioland.svg'
  %a.sub-logo.bio-siegel{:href => "http://www.bioland.de"}
    = image_tag 'home/header/biosiegel.svg'
  %a.sub-logo{:href => "#"}
    = image_tag 'home/header/eu_bio_logo.svg'
  %a.sub-logo.sub-logo-down.eu-button{:href => "http://www.bioland.de"}
    = image_tag 'home/header/eu_logo_start.png'
%header#head
  .logo
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.stick-top#nav{:style => "top: 220px"}
  .navbar-toggler
    .burger
      %span
      %span
      %span
    %span.menu-text
      Menü
  .collapse.navbar-collapse.justify-content-center#navbarNav
    %ul.navbar-nav
      %li.nav-item.d-none.d-lg-block.logo-fade
        = link_to(home_index_path, style: "padding: .75rem", class: "no-hover") do
          = image_tag "logo.png",{:style => "  position: relative;margin: 0 25px; width: 45px;", :class => "d-inline-block"}
      %li.nav-item
        = link_to "Hofladen", {:controller => "home", :action => "hof"}, :class => "nav-link"
      %li.nav-item
        = link_to "Backwaren", {:controller => "home", :action => "hofladen" }, :class => "nav-link"
        .sub-nav
          .sub-nav-container.d-flex
            = link_to "/shop/kategorie/1", {:style => "background-image: url(#{image_path("shop/broetchen.jpg") })"} do
              %h2 Brötchen
            = link_to "/shop/kategorie/2", {:style => "background-image: url(#{image_path("shop/brot.jpg") })"} do
              %h2 Brot
            = link_to "/shop/kategorie/3", {:style => "background-image: url(#{image_path("shop/kleingebaeck.jpg") })"} do
              %h2 Süße Brötchen & Kleingebäck
      %li.nav-item.d-block.d-sm-none
        = link_to "Öffnungszeiten", {:controller => "home", :action => "hofladen", :anchor => "openhour" }, :class => "nav-link"
      %li.nav-item
        = link_to "Obst/Gemüse", {:controller => "home", :action => "fw" }, :class => "nav-link"
      %li.nav-item
        = link_to "Fleisch/Wurst", {:controller => "home", :action => "biogas" }, :class => "nav-link"
      %li.nav-item
        = link_to "Milchprodukte", {:controller => "home", :action => "ausbildung" }, :class => "nav-link"
      %li.nav-item
        = link_to "Sonstiges", {:controller => "home", :action => "kontakt" }, :class => "nav-link"
      %li.nav-item
        %a.no-hover.tooltip2(href="#"){:style => "font-size: 2rem;padding: 15px;"}
          %span.fi.flaticon-farm-products 
        = render :partial => "layouts/shop/cartbox"

      %li.nav-item
        %a.no-hover(href="#"){:style => "font-size: 2rem;padding: 15px;"}
          %span.fi.flaticon-farmer 
        .user-box
          .card
            .card-body
              %h3.card-title.mt-3.mb-4.text-orange Mein Konto
              %form.mb-0
                .form-group
                  .input-group
                    %input.form-control.p-4{:name => "", :placeholder => "Email", :type => "text"}/
                .form-group
                  .input-group
                    %input.form-control.p-4{:name => "", :placeholder => "Passwort", :type => "password"}/
                .form-group
                  %button.btn.btn-success.btn-block.my-0{:type => "submit"} Login
                .form-group.mb-0
                  %a.no-hover.text-orange{:href => "#"} Passwort vergessen

app/views/layouts/shop/_header_small.html.haml
%nav#nav.navbar.navbar-expand-lg.navbar-light.bg-light.fixed-top.box-shadow.fixed
  = link_to(home_index_path, style: "padding: 0", class: " navbar-brand d-lg-none") do
    = image_tag "logo.png",{:style => "  position: relative;margin: 10px 25px; width: 45px;", :class => "d-inline-block"}
  %div.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse"}
    .burger
      %span
      %span
      %span
    %span.menu-text
      Menü
  #navbarNav.collapse.navbar-collapse.justify-content-center
    %ul.navbar-nav
      %li.nav-item.d-none.d-lg-block
        = link_to(home_index_path, style: "padding: .75rem", class: "no-hover") do
          = image_tag "logo.png",{:style => "  position: relative;margin: 0 25px; width: 45px;", :class => "d-inline-block"}
      %li.nav-item
        = link_to "Voglerhof", {:controller => "home", :action => "hof"}, :class => "nav-link"
      %li.nav-item
        = link_to "Hofladen", {:controller => "home", :action => "hofladen" }, :class => "nav-link"
      %li.nav-item.d-block.d-sm-none
        = link_to "Öffnungszeiten", {:controller => "home", :action => "hofladen", :anchor => "openhour" }, :class => "nav-link"
      %li.nav-item
        = link_to "Ferienwohnung", {:controller => "home", :action => "fw" }, :class => "nav-link"
      %li.nav-item
        = link_to "Biogasanlage", {:controller => "home", :action => "biogas" }, :class => "nav-link"
      %li.nav-item
        = link_to "Ausbildung", {:controller => "home", :action => "ausbildung" }, :class => "nav-link"
      %li.nav-item
        = link_to "Kontakt", {:controller => "home", :action => "kontakt" }, :class => "nav-link"

:css
  .navbar-toggler {
  	margin: 0 1rem 0 0 ;
  }

app/views/layouts/shop/shop.html.haml
%head
  %title= content_for?(:title) ? yield(:title) : "Voglerhof | Kirchbrak"

  = stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track' => true
  = stylesheet_link_tag 'shop', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = favicon_link_tag asset_path('favicon.ico')
  = display_meta_tags site: 'Voglerhof | Kirchbrak', description: "Aus Überzeugung bio – schon seit 1989. Erfahren Sie mehr über den Voglerhof und unsere Arbeitsweise.", keywords: "Voglerhof, Bio, Bioland, Kirchbrak, Ferienwohnung, Biogas, Ausbildung, Hofladen"
  = csrf_meta_tags
  %link{:href => "https://fonts.googleapis.com/css?family=Lato:300,300i,400,700|Arvo:400,700", :rel => "stylesheet"}

  %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  /[if lt IE 9] <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
  - if Rails.env.production?
    = render :partial => "layouts/analytics"
%body
  = render :partial => 'layouts/shop/header'
  .content-container.bg-green.container-fluid{:style => "margin-top: 221px"}
    = yield
    .footer{:style => (action_name == 'index' || action_name == 'ausbildung' || action_name == 'hofladen' || action_name == 'kontakt' ? "margin-top: 0px" : "margin-top: 200px; z-index: 9999")}
      = render :partial => 'layouts/shop/footer'
  .cookie-notice.fixed-bottom
    %span
      Um unsere Webseite für Sie optimal zu gestalten und fortlaufend verbessern zu können, verwenden wir Cookies. Durch die weitere Nutzung der Webseite stimmen Sie der Verwendung von Cookies zu.
      Weitere Informationen zu Cookies erhalten Sie in unserer
      = link_to "Datenschutzerklärung", {:controller => "home", :action => "kontakt" }
    %span.btn.btn-small.btn-primary.float-right.agree OK

app/views/shop/index.html.haml
.row.first-section.roomy-40.max-width.mx-lg-5.mx-md-2
  .col-xl-9.col-lg-12.my-md-4
    %h1= @hello
    %h1= @hello
    %h1= @hello
    %h1= @hello
    %h1= @hello
    %h1= @hello
    %h1= @hello
    %h1= @hello
    %h1= @hello

app/views/shop/kasse.html.haml
.row.max-width.mx-lg-5.mx-md-2
  .col-md-12.mt-5.mb-3
    %h2.text-orange Kasse
.row.first-section.max-width.mx-lg-5.mx-md-2 
  .col-md-8
    .card.mb-4.warenkorb
      .card-body.px-4
        %h4.card-title.mb-4.text-muted.py-3.pl-2.sub-header Besteller
        %form{:action => ""}
          .row
            .form-group.col-sm-6
              %label Vorname
              %input.form-control{:placeholder => "", :type => "text"}/
            .form-group.col-sm-6
              %label Nachname
              %input.form-control{:placeholder => "", :type => "text"}/
            .form-group.col-sm-6
              %label Telefon
              %input.form-control{:type => "text", :value => ""}/
            .form-group.col-sm-6
              %label Email
              %input.form-control{:placeholder => "", :type => "email"}/
    .card.mb-4.warenkorb
      .card-body.px-4
        %h4.card-title.mb-4.text-muted.py-3.pl-2.sub-header Abholdatum
        .row
          .form-group.col-sm-6
            %input.form-control{:placeholder => "10.05.2021", :type => "text"}/
    .card.warenkorb
      .card-body.px-4
        %h4.card-title.mb-4.text-muted.py-3.pl-2.sub-header Bezahlung
        .form-check.mb-2
          %input#exampleRadios1.form-check-input{:checked => "checked", :name => "exampleRadios", :type => "radio", :value => "option1"}/
          %label.form-check-label{:for => "11"}
            Barzahlung vor Ort
        .form-check.mb-2
          %input#exampleRadios2.form-check-input{:name => "exampleRadios", :type => "radio", :value => "option2"}/
          %label.form-check-label{:for => "exampleRadios2"}
            PayPal
        .form-check.mb-2
          %input#exampleRadios2.form-check-input{:name => "exampleRadios", :type => "radio", :value => "option3"}/
          %label.form-check-label{:for => "exampleRadios"}
            Vorabüberweisung

  
  .col-md-4
    .card.warenkorb
      .card-body
        %table.table.table-borderless.table-shopping-cart.mb-0
          %thead.text-muted
            %tr.small.text-uppercase{style: "border-bottom: 1px solid rgba(0, 0, 0, 0.1);"}
              %th.py-3.font-weight-normal{:scope => "col", style: "font-size: .85rem"} Gesamt
              %th 
          %tbody
            %tr
              %td
                %p Summe
              %td.text-right.py-0
                %p 10,55 €
            %tr
              %td.py-0
                %small.text-muted MwSt. 19%
              %td.text-right.py-0
                %small.text-muted 2,55 €
            %tr
              %td
                %p.font-weight-bold Gesamt
              %td.text-right
                %p.font-weight-bold 12,55 €
        .form-group.mt-3
          %a.btn.btn-success.btn-small.btn-block.text-white.no-hover.my-0{:type => "submit"} Bestellen
        .form-group.mt-3.px-3.text-center.mb-0
          %small.text-muted.mt-4
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Pariatur modi officiis voluptatem natus.

app/views/shop/kategorie.haml
.row.max-width.mx-lg-5.mx-md-2
  .col-md-12.my-4
    .brotkrumen
      %ul 
        %li 
          = @kategorie.name
.row.first-section.max-width.mx-lg-5.mx-md-2 
  - @produkts.each do |produkt|
    .col-md-4
      %figure.card.card-product-grid.card-lg.mb-5
        = link_to produkt, {class: "img-wrap"} do
          - if produkt.produktbild.present?
            = image_tag(produkt.produktbild, width: "100%", class: "")
          - else
            .pt-5.text-orange
              kein Bild vorhanden  
        %figcaption.info-wrap.align-items-center
          %h3.text-orange.mb-0
            = produkt.name
        .bottom-wrap.d-flex.align-items-center
          .mr-3
            %h3.mb-0.text-green{:style => "font-size: 1rem"}
              = number_to_currency(produkt.preis, {unit: 'Euro'})
          .ml-auto.form-inline
            %select.form-control.mr-2
              %option 1
              %option 2
              %option 3
              %option 4
              %option 5
              %option 6
              %option 7
              %option 8
              %option 9
            %a.my-0.px-3.add-to-cart{:href => "#", "data-placement" => "top", "data-toggle" => "tooltip", :title => "zum Warenkorb hinzufügen"}
              -# %i.fa.fa-shopping-cart
              %i.fi.flaticon-farm-products 

app/views/shop/produkt.html.haml
.row.max-width.mx-lg-5.mx-md-2
  .col-md-12.mt-5.mb-3
    %h2.text-orange Weizenbrötchen
.row.first-section.max-width.mx-lg-5.mx-md-2 



  
  .col-md-8
    .sub-header.text-uppercase.text-yellow2.py-3.pl-2 Informationen


  .col-md-4
    .card.warenkorb
      .card-body
        %img.w-100{:src => image_path("shop/broetchen2.png")}
        .form-group
          %label Menge
          %select.form-control
            %option 1
            %option 2
            %option 3
            %option 4
        .form-group.mb-0
          %a.btn.btn-success.btn-small.btn-block.text-white.no-hover.my-0{:type => "submit"} zum Warenkorb

app/views/shop/produktliste.html.haml
.row.max-width.mx-lg-5.mx-md-2
  .col-md-12.my-4
    .brotkrumen
      %ul 
        %li 
          Backwaren
        %li 
          Brötchen
.row.first-section.max-width.mx-lg-5.mx-md-2 
  .col-md-4
    %figure.card.card-product-grid.card-lg
      %a.img-wrap{:href => "#"}
        %img{:src => image_path("shop/broetchen2.png")}
      %figcaption.info-wrap.align-items-center
        %h3.text-orange.mb-0
          Weizenbrötchen
      .bottom-wrap.d-flex.align-items-center
        .mr-3
          %h3.mb-0.text-green{:style => "font-size: 1rem"} 0,55 Euro
        .ml-auto.form-inline
          %select.form-control.mr-2
            %option 1
            %option 2
            %option 3
            %option 4
            %option 5
            %option 6
            %option 7
            %option 8
            %option 9
          %a.my-0.px-3.add-to-cart{:href => "#", "data-placement" => "top", "data-toggle" => "tooltip", :title => "zum Warenkorb hinzufügen"}
            -# %i.fa.fa-shopping-cart
            %i.fi.flaticon-farm-products 
  
  .col-md-4
    %figure.card.card-product-grid.card-lg
      %a.img-wrap{:href => "#"}
        %img{:src => image_path("shop/broetchen2.png")}
      %figcaption.info-wrap.align-items-center
        %h3.text-orange.mb-0
          Weizenbrötchen
      .bottom-wrap.d-flex.align-items-center
        .mr-3
          %h3.mb-0.text-green{:style => "font-size: 1rem"} 0,55 Euro
        .ml-auto.form-inline
          %select.form-control.mr-2
            %option 1
            %option 2
            %option 3
            %option 4
            %option 5
            %option 6
            %option 7
            %option 8
            %option 9
          %a.my-0.px-3.add-to-cart{:href => "#", "data-placement" => "top", "data-toggle" => "tooltip", :title => "zum Warenkorb hinzufügen"}
            -# %i.fa.fa-shopping-cart
            %i.fi.flaticon-farm-products 
  
  .col-md-4
    %figure.card.card-product-grid.card-lg
      %a.img-wrap{:href => "#"}
        %img{:src => image_path("shop/broetchen2.png")}
      %figcaption.info-wrap.align-items-center
        %h3.text-orange.mb-0
          Weizenbrötchen
      .bottom-wrap.d-flex.align-items-center
        .mr-3
          %h3.mb-0.text-green{:style => "font-size: 1rem"} 0,55 Euro
        .ml-auto.form-inline
          %select.form-control.mr-2
            %option 1
            %option 2
            %option 3
            %option 4
            %option 5
            %option 6
            %option 7
            %option 8
            %option 9
          %a.my-0.px-3.add-to-cart{:href => "#", "data-placement" => "top", "data-toggle" => "tooltip", :title => "zum Warenkorb hinzufügen"}
            %i.fi.flaticon-farm-products 