config/routes.rb
Rails.application.routes.draw do

  resources :kategories
  resources :produkts
  resources :warenkorbpositions
  resources :warenkorbs
  resources :bestellpositions
  resources :bestellungs
  resources :feeds do 
    member do
      delete :delete_image_attachment
    end
    get 'details', to: 'feeds#details'
  end
  
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "register" => "users#new"
  post "users" => "users#create"

  get "admin" => "bookings#dashboard"
  get "bestellemail" => "brotbestellscheins#bestellemail"
  put "bst_auf_schein" => "brotbestellscheins#bst_auf_schein"
  get "schein_aus_bst" => "brotbestellscheins#schein_aus_bst"
  get "standard" => "brotbestellungs#standard"
  post "contact" => "home#contactmail"
  post "anfrage_form" => "anfrages#create"
  get "packzettel" => "brotbestellscheins#packzettel"
  get "packzettel_show/:datum" => "brotbestellscheins#packzettel_show"

  resources :brottyps
  resources :openhours
  resources :brotbestellscheins
  resources :brotbestellposis
  resources :brotbestellungs do
    collection { get 'admin_order' }
  end
  resources :brotsortes
  resources :mieters
  resources :fewos
  resources :bookings do
    member do
      get "bestaetigen"
    end
    collection { get 'dashboard' }
  end
  resources :anfrages do
    get "antwort" => "anfrages#antwort"
  end

  get "home/index"
  get "home/hof"
  get "home/biogas"
  get "home/ausbildung"
  get '/home/ferienwohnung', to: 'home#fw', as: "home_fw"
  get "home/getcalendardates"
  get "home/hofladen"
  get "home/kontakt"
  get "home/thanks"

  get "start/index"
  root "home#index"

  get "shop" => "shop#index", as: :shop
  get "shop/produktliste" => "shop#produktliste"
  get "shop/produkt" => "shop#produkt"
  get "shop/warenkorb" => "shop#warenkorb"
  get "shop/kasse" => "shop#kasse"

  get "shop/kategorie/:id" => "shop#kategorie"

  

end

app/models/anfrage.rb
class Anfrage < ApplicationRecord
  validates :name, :presence => true

end

app/models/bestellung.rb
class Bestellung < ApplicationRecord
  belongs_to :user
  has_many :bestellpositions
end

app/models/brotsorte.rb
class Brotsorte < ApplicationRecord
  has_many :brotbestellposi
  belongs_to :brottyp
  has_one_attached :brotbild
  # validates_attachment_content_type :brotbild, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  #validates_attachment_presence :brotbild
end

app/models/brottyp.rb
class Brottyp < ApplicationRecord
  has_many :brotsortes
end

app/models/event.rb
class Event
  attr_accessor :date

  def initialize(date)
    @date = date
  end

  def start_time
    @date
  end
end

app/models/feed.rb
class Feed < ApplicationRecord
    default_scope { order(priority: :asc) }
    has_many_attached :feedbilder
end

app/models/fewo.rb
class Fewo < ApplicationRecord
  acts_as_bookable  time_type: :range,
                    capacity_type: :closed,
                    bookable_across_occurrences: true

end

app/models/kategorie.rb
class Kategorie < ApplicationRecord
  has_many :produkts
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :telefon, :text

  validates :name, :presence => true
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+[a-z]{2,})\z/i, message: "ist ungültig!",:allow_nil => true, :allow_blank => true
end

app/models/mieter.rb
class Mieter < ApplicationRecord
  acts_as_booker time_type: :range, bookable_across_occurrences: true
  def name_with_initial
    "ID: #{id} / #{vorname} #{name}"
  end
end

app/models/openhour.rb
class Openhour < ApplicationRecord
    default_scope { order(reihenfolge: :asc) }
end

app/models/produkt.rb
class Produkt < ApplicationRecord
  has_many :warenkorbpositions
  has_many :bestellpositions
  belongs_to :kategorie
  has_one_attached :produktbild
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bestellungs
  has_many :warenkorbs


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false},
          length: {maximum: 50}, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true,  uniqueness: true
  validates :password, length: {minimum: 5}

end

app/models/warenkorb.rb
class Warenkorb < ApplicationRecord
  belongs_to :user, optional: true
  has_many :warenkorbpositions, :dependent => :destroy 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  protect_from_forgery except: :fw

  def index
    @openhours = Openhour.all
    @feeds = Feed.all.where.not(deaktiviert: true).sort_by(&:priority).reverse
    render layout: 'home/home'
  end

  def hof
    render layout: 'home/home'
  end

  def biogas
    render layout: 'home/home'
  end

  def ausbildung
    render layout: 'home/home'
  end

  def fw
    @calendar_events = Fewo.all.collect(&:bookings).flatten.compact
    render layout: 'home/home'
  end

  def getcalendardates
    calendarDates
    respond_to do |format|
      format.html { }
      format.js { render 'home/getcalendardates'}
    end
  end

  def hofladen
    @openhours = Openhour.all
    render layout: 'home/home'
  end

  def kontakt
    @openhours = Openhour.all
    render layout: 'home/home'
  end

  def thanks
    render layout: 'home/home'
  end

  def contactmail
    @message = Message.new(message_params)
    @recaptcha_valid = verify_recaptcha(model: @message, action: 'contact')
    if @recaptcha_valid && @message.valid?
      ContactMailer.contact_email(@message).deliver
      respond_to do |format|
        format.html { redirect_to controller: 'home', action: 'index' }
        format.js { render 'home/contact-form' }
      end
    else
      respond_to do |format|
        format.html { redirect_to controller: 'home', action: 'index' }
        format.js { render 'home/contact-form' }
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :telefon, :text)
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/fewo_helper.rb
module FewoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mieter_helper.rb
module MieterHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/home/_anfrage_modal.html.haml
#anfrage.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "Anfrage", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content.border-left
      .modal-header
        %h5.modal-title.text-green Ferienwohnung anfragen
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body.anfrage-body
        = form_for :anfrage, :url => anfrage_form_path, :remote => true, :html =>{:class => 'anfrage-form'} do |form|
          .form-group
            %label{:for => "name"} Name
            = form.text_field :name, class: 'form-control', id: "name"
          .form-row
            .form-group.col-6
              %label{:for => "email"} E-Mail
              = form.text_field :email, class: 'form-control', id: "email"
            .form-group.col-6
              %label{:for => "telefon"} Telefon
              = form.text_field :telefon, class: 'form-control', id: "telefon"
          .form-row
            .form-group.col-6
              %label{:for => "anzahlPersonen"} Datum
              = form.text_field :daterange, class: 'form-control daterange', placeholder: 'Datum'
            .form-group.col-6
              %label.label Anzahl Pers.
              = form.select :anzahl, options_for_select(["1", "2", "3", "4", "5", "6"]),{}, {class: 'form-control '}
          .form-group
            %label{:for => "name"} Nachricht
            = form.text_area :nachricht, class: 'form-control', id: "nachricht"
          .form-group
            .form-check
              = form.check_box :datenschutz, {:class => "form-check-input"}, "1", "0"
              %label.form-check-label{:for => "datenschutzCheck"}
                Ich habe die
                = link_to "Datenschutzerklärung", {:controller => "home", :action => "kontakt" }, {:style => "color: #f3953e; font-size: inherit"}
                zur Kenntnis genommen. Ich stimme zu, dass die von mir übermittelten Daten ausschließlich zur Beantwortung meiner Anfrage verwendet werden.

          %button.btn.btn-small.pull-right{:href => "/", :style => "width: 100%",:type => "submit"}
            %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
            Anfrage absenden
        .form-notice-anfrage
      .modal-footer
        %button.btn.btn-primary{"data-dismiss" => "modal", :type => "button"} Schliessen

app/views/home/_calendar.html.haml
= month_calendar events: @calendar_events, attribute: :time_start, end_attribute: :time_end do |date, meetings|
  = date.day

app/views/home/_carousel.html.haml
#carousel
  .slide-container.container-fluid.border-bottom
    .row{:style => "min-height:100%"}
      .slide-part.left.col-lg-7.col-md-6.no-gutter.d-none.d-md-block.d-none.d-md-block.slide-img{:style => "background-image: url(#{image_path("home/slider/hof_fruehling.jpg")})"}
      .slide-part.right.col-lg-5.col-md-6
        %span.fi.flaticon-farm
        %h3 Der Voglerhof
        %p
          Aus Überzeugung bio – schon seit 1989. Erfahren Sie mehr über den Hof und unsere Arbeitsweise.
        = link_to(home_hof_path, class: "btn") do
          %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
          zum Voglerhof
  .slide-container.container-fluid.border-bottom
    .row{:style => "min-height:100%"}
      .slide-part.left.col-lg-7.col-md-6.no-gutter.d-none.d-md-block.slide-img{:style => "background-image: url(#{image_path("home/slider/hofladen.jpg")})"}
      .slide-part.right.col-lg-5.col-md-6
        %span.fi.flaticon-milk-products
        %h3 Der Hofladen
        %p
          Bioprodukte direkt vom Erzeuger und ein liebevoll zusammengestelltes Biovollsortiment möglichst aus der Region – genau das finden Sie bei uns im Hofladen.
        = link_to(home_hofladen_path, class: "btn") do
          %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
          zum Hofladen
  .slide-container.container-fluid.border-bottom
    .row{:style => "min-height:100%"}
      .slide-part.left.col-lg-7.col-md-6.no-gutter.d-none.d-md-block.slide-img{:style => "background-image: url(#{image_path("home/fewo/fewo2.jpg") })"}
      .slide-part.right.col-lg-5.col-md-6
        %span.fi.flaticon-hay-roll
        %h3 Ferien auf dem Bauernhof
        %p
          Sie suchen ein ruhiges und gemütliches Plätzchen zum „Pause machen“ – dann schauen Sie sich unsere Ferienwohnung an.
        = link_to(home_fw_path, class: "btn") do
          %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
          zur Ferienwohnung
  .slide-container.container-fluid.border-bottom
    .row{:style => "min-height:100%"}
      .slide-part.left.col-lg-7.col-md-6.no-gutter.d-none.d-md-block.slide-img{:style => "background-image: url(#{image_path("home/slider/biogas2.jpg") })"}
      .slide-part.right.col-lg-5.col-md-6
        %span.fi.flaticon-rye
        %h3 Energie aus Biogas!
        %p
          Aus Gülle und Mist Energie machen?! Kein Problem, bei uns macht das die „dicke Berta“ – so lautet der Spitzname für unsere Biogasanlage.
        = link_to(home_biogas_path, class: "btn") do
          %i.fa.fa-angle-double-right
          zum Biogas

app/views/home/ausbildung.html.haml
- content_for :title, " Ausbildung | Voglerhof"

.row
  .col-md-7.m-top-100.ausbildung-text
    %h1.text-yellow.text-center-sm Ausbildung
    .divider-left.center
    %p
      Seit 1986 bieten wir jungen und interessierten Leuten die Möglichkeit unseren Hof kennenzulernen und Berufserfahrung zu sammeln. Durch mehr als 50 Praktikanten/-innen, Auszubildende und Freiwillig Ökologische Helfer/-innen haben wir auch eine Menge gelernt.
    %p
      Seit 2003 haben wir uns auf die Ausbildung im Bereich Landwirtschaft spezialisiert. Hauptgebiet der Ausbildung liegt in der Milchviehhaltung, im Ackerbau und auch der Biogasanlage.
    %p
      Karl-Heinz und Barbara haben ein Praktikum bzw. eine Lehre auf verschiedenen Betrieben gemacht und im Anschluss in Hohenheim Landwirtschaft studiert. Sebastian hat in Australien auf verschiedenen Betrieben gearbeitet und im Anschluss Landwirtschaft in Göttingen studiert. Vor dem Einstieg in den Betrieb hat er in der Landesanstalt für Landwirtschaft in München gearbeitet.
  .col-md-4.offset-md-1.bg-yellow2.ausbildung-info-block
    .vertical-align-center
      %h2.text-green
        %span.fi.flaticon-farmer.fi-big
        Wie kannst du dich bei uns bewerben?
      %p.text-green
        Du solltest viel Interesse an der ökologischen Landwirtschaft mitbringen, das BGJ Agrar besucht und möglichst einen Führerschein Klasse T haben.
      %p.text-green
        Am besten rufst Du erstmal an, um dich zu erkundigen, ob noch ein Ausbildungsplatz für die gewünschte Zeit frei ist. Wenn ja – dann schicke uns doch bitte eine vollständige Bewerbung mit Lebenslauf und Zeugnis. Ein gutes Vorstellungsgespräch zum Kennen lernen und ein ca. drei tägiges Probearbeiten finden wir für beide Seiten wichtig.

app/views/home/fw.js.erb
$(".calendar").html("<%= escape_javascript render(partial: "calendar", locals: {events: @events}) %>");
// $(".loading").toggle();
// $(".calendar").toggle();

app/views/home/getcalendardates.js.erb
$(".calendar").html("<%= escape_javascript render(partial: "calendar", locals: {events: @events}) %>");
$(".loading").toggle();
$(".calendar").toggle();

app/views/home/hofladen.html.haml
- content_for :title, "Hofladen | Voglerhof"

.row

  .col-lg-7.roomy-100.roomy-md{:style => "padding: 0 5% 15% 5%"}
    %h1.text-yellow.text-center-sm Der Hofladen
    .divider-left.center
    %p
      Sie finden ihn gleich rechts vor der Hofeinfahrt und werden vielleicht überrascht sein, in einem kleinen Dorf so ein leckeres biologisches Vollsortiment zu finden.
    %p
      Die eigenen Produkte sind Milch, Joghurt und viele verschiedene Sorten Wurst und Fleisch.
      Sie werden ergänzt von den regionalen Erzeugnissen unserer Biolandkollegen vom Marienhof und der Familie Bossow mit Gemüse, Kartoffeln, Eiern sowie frischem Brot und Brötchen vom Backhaus Wegener.
    %p
      Vom Naturkosthandel wird das Angebot so abgerundet, dass kaum ein Wunsch offen bleibt - besonders zu nennen ist das geschmackvolle Käsesortiment.
    %p
      Besonders am Herzen liegt dem Hofladenteam, das Sortiment mit den Kundinnen und Kunden zusammen weiter zu entwickeln, Anregungen und Wünsche werden gern aufgenommen. Bei vielen kleinen und großen Kunden gehört „Kühe-und-Trecker-Gucken“ mit zum Einkauf.
    %p
      Hier erleben sie Wachsen und Ernten der Lebensmittel im Jahreslauf!
    .row
      .col
        %h3.text-yellow2.mb-1.mt-4 Bildergalerie
        .gallery2-container
          .gallery2-item.hofladen-gallery-item
            = image_tag 'home/hofladen/hofladen1.jpg', :class => " float-left img-fluid  mb-3"
            .gallery2-hover
          .gallery2-item.hofladen-gallery-item
            = image_tag 'home/hofladen/hofladen2.jpg', :class => " float-left img-fluid  mb-3"
            .gallery2-hover
          .gallery2-item.hofladen-gallery-item
            = image_tag 'home/hofladen/hofladen5.jpg', :class => " float-left img-fluid  mb-3"
            .gallery2-hover
          .gallery2-item.hofladen-gallery-item
            = image_tag 'home/hofladen/hofladen3.jpg', :class => " float-left img-fluid  mb-3"
            .gallery2-hover




  .col-lg-2.bg-yellow2.hofladen-info-block#openhour
    .vertical-align-center{:style => "margin: -5% auto 0;"}
      - if @openhours.present?
        %div
          %h4
            %span.fi.flaticon-farm.fi-big
            &nbsp
            Öffnungszeiten
            .list-group.list-group-flush{:style => "margin:0"}
            - @openhours.each do |openhour|
              - if !openhour.geschlossen
                .list-group-item{:class => (openhour.spezial ? "open-at-important" : ""), :style => "font-weight: 300"}
                  - if openhour.without_time
                    = "#{openhour.tag}"
                  - else
                    = "#{openhour.tag}: #{openhour.start.strftime("%H:%M")} - #{openhour.ende.strftime("%H:%M")}"
              - else
                .list-group-item{:class => (openhour.spezial ? "open-at-important" : ""), :style => "font-weight: 300" }
                  = "#{openhour.tag}: geschlossen"
      %h4
        .span{:style => "margin-top: 1.5rem"} Einkaufs(wunsch)zettel
        .span{:style => "font-weight: 300; line-height: 1.4rem;margin-top: 0.5rem"}
          Wir möchten Ihnen anbieten, Ihren Einkauf so stressfrei wie möglich zu gestalten! Senden Sie uns Ihren Einkaufs(wunsch)zettel bis zum Vortag 14.00 Uhr an
          %a{:href => "mailto:barbara@voglerhof.de", :style => "color: #f3953e !important"}barbara@voglerhof.de,
          wir packen es in ein Kistchen. Dann können Sie sich noch dazu holen, was Ihnen gefällt und alles ist fertig...

      -if false #Setting["bst_inactive"] == false
        %h4{:class => ( @openhours.present? ? "m-top-80" : "")}
          %span.fi.flaticon-harvest.fi-big
          Brotbestellung
        %p.text-green{:style => "font-size: 1rem;line-height: 1.5rem"}
          Sie können online Ihr Brot vorbestellen und am gewünschen Tag bei uns im Hofladen abholen.
        %div.not-allowed
          = link_to new_brotbestellung_path, { class:[ ("btn btn-small"), (:disabled if Setting["bst_inactive"] == true) ] } do
            %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
            bestellen
      - else
        %div.d-none.d-lg-block{:style => "height: 15rem;"}


  .col-lg-3.no-gutter{:style => "padding-top: 0"}
    .img-holder{:style => "height: 65rem"}
      .img-item{:style => "background-image: url(#{image_path("home/hofladen/hofladen6.jpg") })"}

app/views/home/index.html.haml
.row.first-section.roomy-40.max-width.mx-lg-5.mx-md-2
  .col-xl-9.col-lg-12.my-md-4
    = render 'carousel'
  .col-xl-3.col-lg-12.my-md-4.my-4
    .info-box.border-bottom
      %h3 Infos &amp; Aktuelles
      .box-wrapper
        - if @feeds.size > 0
          - @feeds.each do |feed|
            .box-item
              %h4{:style => "margin-bottom:0.3rem"}
                %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
                = feed.title
              %p.text-green{style:"margin-bottom: 0.3rem"}
                = feed.text.html_safe
              - if feed.text_details.present? && feed.title_details.present?
                = link_to "mehr lesen...", feed_details_path(feed), {class: "text-orange",style:"font-weight: 400;margin-bottom: 0.5rem"}
              - if feed.feedbilder.size > 0 && feed.vorschaubild
                .image-wrapper{style: "position:relative"}
                  = image_tag(feed.feedbilder.first, width: "100%", class: "")
                  .image-hover
                - if feed.feedbilder.size > 1 
                  - feed.feedbilder[1..-1].each do |bild|
                    = image_tag(bild, width: "100%", style: "display:none")
        - else
          %h4.text-orange keine aktuellen News

      .info-control
        %h4.text-orange#expand-news
          %i.fa.fa-angle-double-right
          Übersicht
        #scroll-down-animation
          %span.mouse
            %span.move

.row.max-width.mx-lg-5.mx-md-2
  .col-lg-5.text-yellow.roomy-120.text-center-md.roomy-md.no-roomy
    %h1 Der Voglerhof
    .divider-left.center
    %h5
      Aus Überzeugung bio – schon seit 1989.
      %br
      Erfahren Sie mehr über den Hof und was es bei uns zu entdecken gibt. Und sowieso, warum eigentlich Bio?
    -# %h5
      Lorem ipsum dolor sit amet, consectetur adipisicing
    = link_to(home_hof_path, class: "btn btn-primary") do
      %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
      mehr
  .col-lg-7.roomy-80.roomy-md
    .img-holder.hover-effect
      .img-item.hof-gallery-item.border-bottom.hover{:style => "background-image: url(#{image_path("home/content/content2.jpg") })"}
        .overlay
      .img-item.hof-gallery-item.border-bottom{:style => "background-image: url(#{image_path("home/hofladen/hofladen7.jpg") })"}
        .overlay
      .img-item.hof-gallery-item.border-bottom{:style => "background-image: url(#{image_path("home/content/trecker2.jpg")})"}
        .overlay
.row.bg-yellow2.roomy-90.justify-content-center
  .col-md-11
    .row
      .col-lg-4.col-md-12.text-center-sm.my-md-3.px-md-5
        - if false #Setting["bst_inactive"] == false
          %h2{:style => "line-height: 1.5"}
            %span.fi.flaticon-harvest.fi-big.extra-m-bottom
            %br
            Brotbestellung
          %p.text-green
            Brot und Brötchen schnell und unkompliziert vorbestellen – ganz bequem jetzt online!
          = link_to(home_hofladen_path, class: "btn btn-small") do
            %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
            zur Brotbestellung
        - else
          %h2{:style => "line-height: 1.5"}
            %span.fi.flaticon-farm.fi-big.extra-m-bottom
            %br
            Ferienwohnung
          %p.text-green
            Sie suchen ein ruhiges und gemütliches Plätzchen zum „Pause machen“ – dann schauen Sie sich unsere Ferienwohnung.
          = link_to(home_fw_path, class: "btn btn-small") do
            %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
            zur Ferienwohnung

      .col-lg-4.col-md-12.text-center-sm.my-md-3.px-md-5
        %h2{:style => "line-height: 1.5"}
          %span.fi.flaticon-farm-products.fi-big.extra-m-bottom
          %br
          Hofladen
        %p.text-green
          Frische Milch oder frisches regionales Gemüse – biologisch! Das und noch mehr finden Sie bei uns im Hofladen.
        = link_to(home_hofladen_path, class: "btn btn-small") do
          %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
          zum Hofladen
      .col-lg-4.col-md-12.text-center-sm.my-md-3.px-md-5
        %h2{:style => "line-height: 1.5"}
          %span.fi.flaticon-farmer.fi-big.extra-m-bottom
          %br
          Ausbildung
        %p.text-green
          Sucht Ihr einen Ausbildungsplatz in der Landwirtschaft mit abwechslungsreichen Betriebszweigen?
        = link_to(home_ausbildung_path, class: "btn btn-small") do
          %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
          mehr Infos


.row.roomy-150
  .col-md-12.text-center.text-yellow
    %h1.too-long Ferienwohnung
    .divider-center
    .img-holder.roomy-50{:style => "margin:0 -15px"}
      .img-item.border-bottom.fw-gallery-item{:style => "background-image: url(#{image_path("home/fewo/fewo1.jpg") })"}
      .img-item.border-bottom.fw-gallery-item{:style => "background-image: url(#{image_path("home/fewo/fewo10.jpg") })"}
      .img-item.border-bottom.fw-gallery-item{:style => "background-image: url(#{image_path("home/fewo/fewo2.jpg") })"}
    %p
      In einem liebevoll restaurierten Fachwerkhaus befindet sich die Ferienwohnung mit bis zu sechs Schlafplätzen.
      %br
      Geräumig und gleichzeitig sehr gemütlich – Lust auf Ferien im Weserbergland?
    = link_to(home_fw_path, class: "btn btn-primary btn-small") do
      %i.fa.fa-angle-double-right{"aria-hidden" => "true"}
      Ferienwohnung buchen

.row#eu.mb-5
  .col-md-12.text-center.text-yellow.pb-4
    %h1.too-long EU-Förderung
    .divider-center
    .row.justify-content-center.mt-5
      .col-md-4
        = image_tag 'home/eu_gross.png', :class => "img-fluid  mb-3 rounded ", :style => ""
      .col-md-5.text-left.ml-md-4
        %h3.mt-4{:style => "overflow-wrap: break-word"}
          Ökologischer/biologischer Landbau
        %p
          Mit dieser Maßnahme werden landwirtschaftliche Betriebe bei der Einführung
          von ökologischer Landwirtschaft und deren Beibehaltung unterstützt
        %h3.mt-4{:style => "overflow-wrap: break-word"}
          „Agrarumwelt- und Klimaschutzmaßnahmen"
        %p
          Mit diesen Maßnahmen werden landwirtschaftliche Betriebe bei der Erhaltung
          und Verbesserung der Umweltsituation unterstützt. Ziel ist eine nachhaltige
          und ressourcenschonende Bewirtschaftung in Bezug auf Artenvielfalt, Boden,
          Wasser und den Schutz des Klimas.
        -# %h3.mt-4{:style => "overflow-wrap: break-word"}
        -#   Ausgleichszulage
        -# %p
        -#   Mit dieser Maßnahme werden landwirtschaftliche Betriebe in Gebieten
        -#   unterstützt, die aus erheblichen naturbedingten Gründen benachteiligt sind.
        -#   Ziel ist die dauerhafte Nutzung durch die Landwirtschaft und der Erhalt von
        -#   nachhaltigen Bewirtschaftungsformen.
        %h3.mt-5
          %a.too-long-sm{:href => "http://www.eler.niedersachsen.de", :rel => "noopener noreferrer", :target => "_blank"}
            www.eler.niedersachsen.de


.row
  .col.no-gutter
    -# #map.border-bottom{:style => 'height:550px; width: 100%'}




%script{:async => true, :defer => true, :src => "https://maps.googleapis.com/maps/api/js?key=#{ENV["GMAP_API"]}&callback=initMap"}

:javascript
  /* GOOGLE MAPS */
  function initMap() {

    var myLatLng = {lat: 51.9658124, lng: 9.5735824};

    var map = new google.maps.Map(document.getElementById('map'), {
      center: myLatLng,
      scrollwheel: false,
      zoom: 15
    });

    var marker = new google.maps.Marker({
      map: map,
      position: myLatLng,
    });
  }

app/views/home/thanks.html.haml
.ui.grid.container
  .sixteen.wide.column
    %h2.text-yellow2.m-top-50 Danke für Ihre Bestellung!